Document: oncilla-sim
Title: Debian oncilla-sim Manual
Author: <insert document author here>
Abstract: This manual describes what oncilla-sim is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/oncilla-sim/oncilla-sim.sgml.gz

Format: postscript
Files: /usr/share/doc/oncilla-sim/oncilla-sim.ps.gz

Format: text
Files: /usr/share/doc/oncilla-sim/oncilla-sim.text.gz

Format: HTML
Index: /usr/share/doc/oncilla-sim/html/index.html
Files: /usr/share/doc/oncilla-sim/html/*.html
